postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: $:g6oZ!WZ_i6de<<8ehQ]LI5RYiP
      port: 5434
      dbname: postgres
      schema: simfin_dbt
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
